/*==============================================================================
    Stata Cross-Validation for MATLAB-Python Econometrics Bridge (pyBridge)
    
    This do-file runs all econometric models supported by pyBridge and outputs
    results for cross-validation with MATLAB/statsmodels/linearmodels.
    
    Data: stata_test_data.csv (generated by generate_stata_test_data.m)
    
    Models tested:
    1. OLS (nonrobust, HC1, HAC, cluster)
    2. WLS
    3. Binary Logit (HC1 + 5 marginal effects)
    4. Probit (HC1 + 5 marginal effects)
    5. Multinomial Logit (HC1, base=0, base=2)
    6. Ordered Logit
    7. Ordered Probit
    8. Poisson Regression
    9. Negative Binomial
    10. Panel FE (robust, clustered)
    11. Panel RE
    12. Between OLS
    13. Pooled OLS
    14. First Difference
    15. Hausman Test (FE vs RE)
    16. IV/2SLS
    17. IV/LIML
    
    NOTE: Stata's vce(robust) implements HC1 standard errors by default.
          This matches statsmodels cov_type='HC1'.
    
    Author: Auto-generated for pyBridge validation
==============================================================================*/


/*------------------------------------------------------------------------------
    SECTION 0: DATA LOADING AND SETUP
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 0: DATA LOADING AND SETUP"
display as text "=============================================================="
display _newline

clear all
set more off
set linesize 120

* Load data (adjust path as needed for your environment)
* Assumes working directory is the tests folder
import delimited using "stata_test_data.csv", clear

* Display data structure
describe

* Summary statistics
summarize

display _newline
display as result "Data loaded successfully: " _N " observations"
display _newline


/*------------------------------------------------------------------------------
    SECTION 1: OLS REGRESSION (4 variants)
    
    MATLAB pyBridge equivalents:
    - 1.1: sm.ols(formula, data)                    % Classical SE (nonrobust)
    - 1.2: sm.ols(formula, data, 'cov_type','HC1')  % HC1 robust SE
    - 1.3: sm.ols(formula, data, 'cov_type','HAC')  % HAC Newey-West
    - 1.4: sm.ols(formula, data, 'cov_type','cluster', 'groups',groups)
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 1: OLS REGRESSION"
display as text "=============================================================="
display _newline

* 1.1 OLS - Classical (non-robust) Standard Errors
display as text "--------------------------------------------------------------"
display as text "  1.1 OLS - Classical SE (nonrobust)"
display as text "  pyBridge: sm.ols('y_ols ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
reg y_ols X1 X2 X3

display _newline

* 1.2 OLS - HC1 Robust Standard Errors
* NOTE: Stata vce(robust) = HC1 = White's heteroskedasticity-consistent estimator
*       with small-sample correction: V = (n/(n-k)) * V_HC0
display as text "--------------------------------------------------------------"
display as text "  1.2 OLS - HC1 Robust SE"
display as text "  pyBridge: sm.ols('y_ols ~ X1 + X2 + X3', data, 'cov_type','HC1')"
display as text "  NOTE: Stata vce(robust) = HC1"
display as text "--------------------------------------------------------------"
reg y_ols X1 X2 X3, vce(robust)

display _newline

* 1.3 OLS - HAC Newey-West Standard Errors (lag=4)
* NOTE: Stata newey uses Bartlett kernel weights
display as text "--------------------------------------------------------------"
display as text "  1.3 OLS - HAC Newey-West SE (lag=4)"
display as text "  pyBridge: sm.ols('y_ols ~ X1 + X2 + X3', data, 'cov_type','HAC',"
display as text "            'maxlags',4)"
display as text "--------------------------------------------------------------"
newey y_ols X1 X2 X3, lag(4)

display _newline

* 1.4 OLS - Clustered Standard Errors
display as text "--------------------------------------------------------------"
display as text "  1.4 OLS - Clustered SE (by clusterid)"
display as text "  pyBridge: sm.ols('y_ols ~ X1 + X2 + X3', data, 'cov_type','cluster',"
display as text "            'groups',data.clusterid)"
display as text "--------------------------------------------------------------"
reg y_ols X1 X2 X3, vce(cluster clusterid)

display _newline


/*------------------------------------------------------------------------------
    SECTION 2: WEIGHTED LEAST SQUARES (WLS)
    
    MATLAB pyBridge equivalent:
    - sm.wls('y_ols ~ X1 + X2 + X3', data, weights)
    
    NOTE: Stata [aw=weights] uses analytic weights (inverse variance weights)
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 2: WEIGHTED LEAST SQUARES"
display as text "=============================================================="
display _newline

display as text "--------------------------------------------------------------"
display as text "  2.1 WLS - Analytic Weights"
display as text "  pyBridge: sm.wls('y_ols ~ X1 + X2 + X3', data, weights)"
display as text "--------------------------------------------------------------"
reg y_ols X1 X2 X3 [aw=weights]

display _newline


/*------------------------------------------------------------------------------
    SECTION 3: BINARY LOGIT
    
    MATLAB pyBridge equivalents:
    - 3.1: sm.logit(formula, data, 'cov_type','HC1')
    - 3.2: sm.logit(formula, data, 'cov_type','cluster', 'groups',groups)
    - 3.3-3.7: result.get_margeff(...) with various methods
    
    Marginal Effects types:
    - dydx: dy/dx (standard marginal effect)
    - eyex: elasticity (d ln(y) / d ln(x)) = (dy/dx) * (x/y)
    - dyex: semi-elasticity (dy / d ln(x)) = (dy/dx) * x
    - eydx: semi-elasticity (d ln(y) / dx) = (dy/dx) / y
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 3: BINARY LOGIT"
display as text "=============================================================="
display _newline

* 3.1 Logit - HC1 Robust SE
display as text "--------------------------------------------------------------"
display as text "  3.1 Logit - HC1 Robust SE"
display as text "  pyBridge: sm.logit('y_binary ~ X1 + X2 + X3', data, 'cov_type','HC1')"
display as text "--------------------------------------------------------------"
logit y_binary X1 X2 X3, vce(robust)

display _newline

* 3.2 Logit - Clustered SE
display as text "--------------------------------------------------------------"
display as text "  3.2 Logit - Clustered SE"
display as text "  pyBridge: sm.logit(..., 'cov_type','cluster', 'groups',clusterid)"
display as text "--------------------------------------------------------------"
logit y_binary X1 X2 X3, vce(cluster clusterid)

display _newline

* Marginal Effects - estimate model first
quietly logit y_binary X1 X2 X3, vce(robust)

* 3.3 Marginal Effects - AME (Average Marginal Effects)
* dy/dx evaluated at each observation, then averaged
display as text "--------------------------------------------------------------"
display as text "  3.3 Logit Marginal Effects - AME (dydx, overall)"
display as text "  pyBridge: result.get_margeff('at','overall','method','dydx')"
display as text "--------------------------------------------------------------"
margins, dydx(*)

display _newline

* 3.4 Marginal Effects - MEM (Marginal Effects at Means)
* dy/dx evaluated at mean values of all covariates
display as text "--------------------------------------------------------------"
display as text "  3.4 Logit Marginal Effects - MEM (dydx, atmeans)"
display as text "  pyBridge: result.get_margeff('at','mean','method','dydx')"
display as text "--------------------------------------------------------------"
margins, dydx(*) atmeans

display _newline

* 3.5 Marginal Effects - eyex (elasticity at means)
display as text "--------------------------------------------------------------"
display as text "  3.5 Logit Marginal Effects - eyex (elasticity at means)"
display as text "  pyBridge: result.get_margeff('at','mean','method','eyex')"
display as text "--------------------------------------------------------------"
margins, eyex(*) atmeans

display _newline

* 3.6 Marginal Effects - dyex (semi-elasticity at means)
display as text "--------------------------------------------------------------"
display as text "  3.6 Logit Marginal Effects - dyex (at means)"
display as text "  pyBridge: result.get_margeff('at','mean','method','dyex')"
display as text "--------------------------------------------------------------"
margins, dyex(*) atmeans

display _newline

* 3.7 Marginal Effects - eydx (semi-elasticity at means)
display as text "--------------------------------------------------------------"
display as text "  3.7 Logit Marginal Effects - eydx (at means)"
display as text "  pyBridge: result.get_margeff('at','mean','method','eydx')"
display as text "--------------------------------------------------------------"
margins, eydx(*) atmeans

display _newline


/*------------------------------------------------------------------------------
    SECTION 4: PROBIT
    
    MATLAB pyBridge equivalents:
    - 4.1: sm.probit(formula, data, 'cov_type','HC1')
    - 4.2-4.3: result.get_margeff(...)
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 4: PROBIT"
display as text "=============================================================="
display _newline

* 4.1 Probit - HC1 Robust SE
display as text "--------------------------------------------------------------"
display as text "  4.1 Probit - HC1 Robust SE"
display as text "  pyBridge: sm.probit('y_binary ~ X1 + X2 + X3', data, 'cov_type','HC1')"
display as text "--------------------------------------------------------------"
probit y_binary X1 X2 X3, vce(robust)

display _newline

* Marginal Effects
quietly probit y_binary X1 X2 X3, vce(robust)

* 4.2 Probit Marginal Effects - AME
display as text "--------------------------------------------------------------"
display as text "  4.2 Probit Marginal Effects - AME (dydx, overall)"
display as text "  pyBridge: result.get_margeff('at','overall','method','dydx')"
display as text "--------------------------------------------------------------"
margins, dydx(*)

display _newline

* 4.3 Probit Marginal Effects - MEM
display as text "--------------------------------------------------------------"
display as text "  4.3 Probit Marginal Effects - MEM (dydx, atmeans)"
display as text "  pyBridge: result.get_margeff('at','mean','method','dydx')"
display as text "--------------------------------------------------------------"
margins, dydx(*) atmeans

display _newline


/*------------------------------------------------------------------------------
    SECTION 5: MULTINOMIAL LOGIT
    
    MATLAB pyBridge equivalents:
    - 5.1: sm.mlogit(formula, data, 'cov_type','HC1')  % base=0 default
    - 5.2: sm.mlogit(formula, data, 'cov_type','HC1', 'base_category',2)
    
    NOTE: y_multi has 3 categories: 0, 1, 2
          Coefficients are relative to base outcome
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 5: MULTINOMIAL LOGIT"
display as text "=============================================================="
display _newline

* 5.1 MLogit - HC1 Robust SE, base=0
display as text "--------------------------------------------------------------"
display as text "  5.1 MLogit - HC1 Robust SE, base=0"
display as text "  pyBridge: sm.mlogit('y_multi ~ X1 + X2 + X3', data, 'cov_type','HC1')"
display as text "--------------------------------------------------------------"
mlogit y_multi X1 X2 X3, vce(robust) baseoutcome(0)

display _newline

* 5.2 MLogit - HC1 Robust SE, base=2
display as text "--------------------------------------------------------------"
display as text "  5.2 MLogit - HC1 Robust SE, base=2"
display as text "  pyBridge: sm.mlogit(..., 'base_category',2)"
display as text "--------------------------------------------------------------"
mlogit y_multi X1 X2 X3, vce(robust) baseoutcome(2)

display _newline

* 5.3 MLogit - Clustered SE, base=0
display as text "--------------------------------------------------------------"
display as text "  5.3 MLogit - Clustered SE, base=0"
display as text "  pyBridge: sm.mlogit(..., 'cov_type','cluster', 'groups',clusterid)"
display as text "--------------------------------------------------------------"
mlogit y_multi X1 X2 X3, vce(cluster clusterid) baseoutcome(0)

display _newline


/*------------------------------------------------------------------------------
    SECTION 6: ORDERED LOGIT AND PROBIT
    
    MATLAB pyBridge equivalents:
    - 6.1: sm.ordered_logit(formula, data)
    - 6.2: sm.ordered_probit(formula, data)
    
    NOTE: y_ordered has 4 categories: 1, 2, 3, 4
          Reports coefficients and cut points (thresholds)
    
    Note: pyBridge orderedLogit defaults addConstant=false, covType="nonrobust", maxIter=1000
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 6: ORDERED LOGIT AND PROBIT"
display as text "=============================================================="
display _newline

* 6.1 Ordered Logit
display as text "--------------------------------------------------------------"
display as text "  6.1 Ordered Logit"
display as text "  pyBridge: sm.ordered_logit('y_ordered ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
ologit y_ordered X1 X2 X3

display _newline

* 6.2 Ordered Probit
display as text "--------------------------------------------------------------"
display as text "  6.2 Ordered Probit"
display as text "  pyBridge: sm.ordered_probit('y_ordered ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
oprobit y_ordered X1 X2 X3

display _newline


/*------------------------------------------------------------------------------
    SECTION 7: COUNT MODELS (Poisson and Negative Binomial)
    
    MATLAB pyBridge equivalents:
    - 7.1: sm.poisson(formula, data)
    - 7.2: sm.negbin(formula, data)
    
    NOTE: Poisson assumes mean = variance
          Negative Binomial allows overdispersion (variance > mean)
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 7: COUNT MODELS"
display as text "=============================================================="
display _newline

* 7.1 Poisson Regression
* Note: pyBridge poisson now supports covType parameter (e.g., covType="HC1")
display as text "--------------------------------------------------------------"
display as text "  7.1 Poisson Regression"
display as text "  pyBridge: sm.poisson('y_count ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
poisson y_count X1 X2 X3

display _newline

* 7.2 Negative Binomial Regression
display as text "--------------------------------------------------------------"
display as text "  7.2 Negative Binomial Regression"
display as text "  pyBridge: sm.negbin('y_count ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
nbreg y_count X1 X2 X3

display _newline


/*------------------------------------------------------------------------------
    SECTION 8: PANEL DATA MODELS
    
    MATLAB pyBridge equivalents (using linearmodels):
    - 8.1: lm.panel_fe(formula, data, 'entity_effects',true, 'cov_type','robust')
    - 8.2: lm.panel_fe(..., 'cov_type','clustered', 'clusters',entityid)
    - 8.3: lm.panel_re(formula, data)
    - 8.4: lm.between_ols(formula, data)
    - 8.5: lm.pooled_ols(formula, data)
    
    NOTE: Panel structure is entityid (50 entities) x timeid (10 periods)
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 8: PANEL DATA MODELS"
display as text "=============================================================="
display _newline

* Set panel structure
display as text "Setting panel structure: entityid x timeid"
xtset entityid timeid
display _newline

* 8.1 Panel Fixed Effects - Robust SE
display as text "--------------------------------------------------------------"
display as text "  8.1 Panel FE - Robust SE"
display as text "  pyBridge: lm.panel_fe('y_continuous ~ X1 + X2 + X3', data,"
display as text "            'entity_effects',true, 'cov_type','robust')"
display as text "--------------------------------------------------------------"
xtreg y_continuous X1 X2 X3, fe vce(robust)

display _newline

* 8.2 Panel Fixed Effects - Clustered SE (by entity)
display as text "--------------------------------------------------------------"
display as text "  8.2 Panel FE - Clustered SE (by entityid)"
display as text "  pyBridge: lm.panel_fe(..., 'cov_type','clustered',"
display as text "            'clusters',data.entityid)"
display as text "--------------------------------------------------------------"
xtreg y_continuous X1 X2 X3, fe vce(cluster entityid)

display _newline

* 8.3 Panel Random Effects
display as text "--------------------------------------------------------------"
display as text "  8.3 Panel RE"
display as text "  pyBridge: lm.panel_re('y_continuous ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
xtreg y_continuous X1 X2 X3, re

display _newline

* 8.4 Between OLS (uses group means)
display as text "--------------------------------------------------------------"
display as text "  8.4 Between OLS"
display as text "  pyBridge: lm.between_ols('y_continuous ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
xtreg y_continuous X1 X2 X3, be

display _newline

* 8.5 Pooled OLS (ignores panel structure)
display as text "--------------------------------------------------------------"
display as text "  8.5 Pooled OLS"
display as text "  pyBridge: lm.pooled_ols('y_continuous ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"
reg y_continuous X1 X2 X3

display _newline

* 8.6 Hausman Test (FE vs RE)
display as text "--------------------------------------------------------------"
display as text "  8.6 Hausman Test (FE vs RE)"
display as text "  Tests H0: RE is consistent (individual effects uncorrelated"
display as text "  with regressors)"
display as text "--------------------------------------------------------------"
quietly xtreg y_continuous X1 X2 X3, fe
estimates store fe_model
quietly xtreg y_continuous X1 X2 X3, re
estimates store re_model
hausman fe_model re_model

display _newline


/*------------------------------------------------------------------------------
    SECTION 9: FIRST DIFFERENCE ESTIMATOR
    
    MATLAB pyBridge equivalent:
    - lm.first_difference('y_continuous ~ X1 + X2 + X3', data)
    
    NOTE: First differencing removes time-invariant unobserved heterogeneity
          Loses first observation for each entity
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 9: FIRST DIFFERENCE"
display as text "=============================================================="
display _newline

display as text "--------------------------------------------------------------"
display as text "  9.1 First Difference Estimator"
display as text "  pyBridge: lm.first_difference('y_continuous ~ X1 + X2 + X3', data)"
display as text "--------------------------------------------------------------"

* Manual first difference transformation
* Sort by entity and time
sort entityid timeid

* Generate differenced variables
by entityid: gen dy = y_continuous - y_continuous[_n-1]
by entityid: gen dX1 = X1 - X1[_n-1]
by entityid: gen dX2 = X2 - X2[_n-1]
by entityid: gen dX3 = X3 - X3[_n-1]

* Run FD regression (no constant, exclude first period)
reg dy dX1 dX2 dX3 if timeid > 1, noconstant

* Clean up differenced variables
drop dy dX1 dX2 dX3

display _newline


/*------------------------------------------------------------------------------
    SECTION 10: INSTRUMENTAL VARIABLES (IV) MODELS
    
    MATLAB pyBridge equivalents (using linearmodels):
    - 10.1: LinearmodelsWrapper.iv2SLS(y_iv, X_endog, X3, [Z1 Z2])
    - 10.2: LinearmodelsWrapper.iv2SLS(y_iv, X_endog, X3, [Z1 Z2], covType="robust")
    - 10.3: LinearmodelsWrapper.ivLIML(y_iv, X_endog, X3, [Z1 Z2])
    - 10.4: LinearmodelsWrapper.ivGMM(y_iv, X_endog, X3, [Z1 Z2], covType="robust")
    
    NOTE: X_endog is endogenous (correlated with error)
          Z1, Z2 are instruments (correlated with X_endog, uncorrelated with error)
          X3 is exogenous covariate
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 10: INSTRUMENTAL VARIABLES (IV)"
display as text "=============================================================="
display _newline

* 10.1 IV/2SLS - Classical SE
display as text "--------------------------------------------------------------"
display as text "  10.1 IV/2SLS - Classical SE"
display as text "  pyBridge: LinearmodelsWrapper.iv2SLS(y_iv, X_endog, X3, [Z1 Z2])"
display as text "  Endogenous: X_endog"
display as text "  Instruments: Z1, Z2"
display as text "  Exogenous: X3"
display as text "--------------------------------------------------------------"
ivregress 2sls y_iv X3 (x_endog = Z1 Z2)

display _newline

* 10.2 IV/2SLS - Robust SE
display as text "--------------------------------------------------------------"
display as text "  10.2 IV/2SLS - Robust SE (HC1)"
display as text "  pyBridge: LinearmodelsWrapper.iv2SLS(y_iv, X_endog, X3, [Z1 Z2], covType="robust")"
display as text "--------------------------------------------------------------"
ivregress 2sls y_iv X3 (x_endog = Z1 Z2), vce(robust)

display _newline

* 10.3 IV/LIML (Limited Information Maximum Likelihood)
display as text "--------------------------------------------------------------"
display as text "  10.3 IV/LIML"
display as text "  pyBridge: LinearmodelsWrapper.ivLIML(y_iv, X_endog, X3, [Z1 Z2])"
display as text "  NOTE: LIML is more robust to weak instruments than 2SLS"
display as text "--------------------------------------------------------------"
ivregress liml y_iv X3 (x_endog = Z1 Z2)

display _newline

* 10.4 First Stage Diagnostics
display as text "--------------------------------------------------------------"
display as text "  10.4 First Stage Diagnostics"
display as text "  Tests instrument relevance (F > 10 rule of thumb)"
display as text "--------------------------------------------------------------"
quietly ivregress 2sls y_iv X3 (x_endog = Z1 Z2)
estat firststage

display _newline


/*------------------------------------------------------------------------------
    SECTION 11: DIAGNOSTIC TESTS
    
    Additional specification tests commonly used with regression models
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  SECTION 11: DIAGNOSTIC TESTS"
display as text "=============================================================="
display _newline

* Run OLS first for diagnostics
quietly reg y_ols X1 X2 X3

* 11.1 Breusch-Pagan Test for Heteroskedasticity
display as text "--------------------------------------------------------------"
display as text "  11.1 Breusch-Pagan Test for Heteroskedasticity"
display as text "  H0: Constant variance (homoskedasticity)"
display as text "--------------------------------------------------------------"
estat hettest

display _newline

* 11.2 Durbin-Watson Test for Autocorrelation
display as text "--------------------------------------------------------------"
display as text "  11.2 Durbin-Watson Test for Autocorrelation"
display as text "  H0: No first-order autocorrelation"
display as text "  DW ~ 2 suggests no autocorrelation"
display as text "--------------------------------------------------------------"
estat dwatson

display _newline

* 11.3 Variance Inflation Factor (VIF) for Multicollinearity
display as text "--------------------------------------------------------------"
display as text "  11.3 Variance Inflation Factor (VIF)"
display as text "  VIF > 10 suggests serious multicollinearity"
display as text "--------------------------------------------------------------"
vif

display _newline


/*------------------------------------------------------------------------------
    SUMMARY
------------------------------------------------------------------------------*/

display _newline
display as text "=============================================================="
display as text "  VALIDATION SCRIPT COMPLETED"
display as text "=============================================================="
display _newline
display as text "All models have been estimated. Compare results with pyBridge:"
display as text ""
display as text "  Key correspondences:"
display as text "  - Stata vce(robust) = statsmodels HC1"
display as text "  - Stata [aw=weights] = statsmodels WLS"
display as text "  - Stata xtreg, fe = linearmodels PanelOLS with entity_effects"
display as text "  - Stata xtreg, re = linearmodels RandomEffects"
display as text "  - Stata margins, dydx(*) = get_margeff with method='dydx'"
display as text ""
display as text "  Expected precision: coefficients within 1e-6, SE within 1e-4"
display _newline
